
title: My Resume
url: 'https://gsuresh26kr.github.io'
baseurl: '/test-suresh-kumar.github.io' #change it according to your repository name



# Profile information
yourname: Suresh Kumar  ## put your name
title: 'Senior System Engineer'  ## your title
location: Bangalore, India


## Social Profiles
facebook: https://www.facebook.com/gsuresh26kr ## your facebook account url
google plus: https://plus.google.com/106771094875254142492  ## your twitter account url
linkedin: http://www.linkedin.com/pub/suresh-kumar/40/8b4/897  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
